paywater/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("usuarios.urls")),
    path('', include("main_pages.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as AuthViews

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(template_name='login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('logout/', AuthViews.LogoutView.as_view(), name="logout"),
    path('perfil/', views.perfil, name="perfil"),
    path('perfil/atualizar/', views.completar_perfil, name='completar-perfil'),
    path('alterar-senha/', views.alterar_senha, name='alterar-senha'),
    path('deletar-conta/', views.deletar_conta, name='deletar-conta'),
    path('meus-pedidos/', views.tabela_pedidos_cliente, name='tabela_pedidos_cliente'),
     path('pedido/<int:pedido_id>/', views.detalhes_pedido, name='detalhes_pedido'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

class UserPerfil(models.Model):
    usuario = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='user_name')
    nome_completo = models.CharField(max_length=220)
    foto = models.ImageField(upload_to='perfil_fotos/', blank=True,
                             null=True, help_text="Foto de perfil do usuário")
    cpf = models.CharField(max_length=14, help_text="CPF do usuário")
    data_nascimento = models.DateField(
        help_text="Data de nascimento do usuário", default=date(2007, 1, 1))
    cep = models.CharField(max_length=9, help_text="CEP do usuário")
    endereco = models.CharField(
        max_length=220, blank=True, null=True, help_text="Endereço completo")
    estado = models.CharField(
        max_length=2, blank=True, null=True, help_text="Estado da instalação (ex: PI)")
    cidade = models.CharField(
        max_length=100, blank=True, null=True, help_text="Cidade do usuário")
    referencia = models.TextField()

    def __str__(self):
        return f"Perfil {self.usuario.username}"

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserPerfil
from django.core.exceptions import ValidationError
from datetime import date


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("As senhas não coincidem.")

        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        if User.objects.filter(username=username).exists():
            self.add_error(
                'username', 'Este nome de usuário já está em uso. Por favor, escolha outro.')

        if User.objects.filter(email=email).exists():
            self.add_error('email', 'Este e-mail já está em uso.')

        return cleaned_data
    
    
class UserPerfilForm(forms.ModelForm):
    class Meta:
        model = UserPerfil
        fields = ['nome_completo', 'data_nascimento', 'cep',
                  'cpf', 'endereco', 'estado', 'cidade', 'foto','referencia']

    nome_completo = forms.CharField(
        label='Nome Completo',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Digite seu nome completo'})
    )

    data_nascimento = forms.DateField(
        label='Data de Nascimento',
        widget=forms.DateInput(
            attrs={'class': 'form-control', 'type': 'date'}),
        input_formats=['%Y-%m-%d'],  # Garante o formato correto
        required=True  # Para evitar erro se o campo estiver vazio
    )

    cep = forms.CharField(
        label='CEP',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Digite seu CEP'})
    )
    cpf = forms.CharField(
        label='CPF',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Digite seu CPF'})
    )

    endereco = forms.CharField(
        label='Endereço',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Endereço completo'})
    )

    estado = forms.CharField(
        label='Estado',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'readonly': True})
    )

    cidade = forms.CharField(
        label='Cidade',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'readonly': True})
    )

    foto = forms.ImageField(
        label='Foto de Perfil',
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'}),
        required=False  # Torna o campo opcional
    )

    def clean_data_nascimento(self):
        data_nascimento = self.cleaned_data.get('data_nascimento')
        if data_nascimento:
            hoje = date.today()
            idade = hoje.year - data_nascimento.year - \
                ((hoje.month, hoje.day) < (data_nascimento.month, data_nascimento.day))

            if idade < 18:
                raise ValidationError(
                    'Você deve ter pelo menos 18 anos para se registrar.')
        return data_nascimento

usuarios/views.py
from django.contrib.auth.models import User
from django.utils.translation import activate as activate_ptbr
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.decorators import login_required
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import UserPerfil
from .forms import SignUpForm,UserPerfilForm
from django.contrib.auth.views import LoginView
from django.contrib import messages
from main_pages import models as mainModels


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False  # Deixar o usuário inativo até a confirmação
            user.save()

            # Gerar token e UID
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = default_token_generator.make_token(user)

            # Obter o domínio atual
            current_site = get_current_site(request)
            mail_subject = 'Confirme seu email'
            message = render_to_string(
                'activation_email.html',  # Template de e-mail de ativação
                {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': uid,
                    'token': token,
                }
            )

            # Enviar o e-mail
            send_mail(
                mail_subject,
                message,
                'noreply@yourdomain.com',  # Substitua pelo e-mail de envio
                [user.email],
                fail_silently=False,
                html_message=message,  # Definir o conteúdo do e-mail como HTML
            )

            # Adicionar mensagem de sucesso
            messages.success(
                request, 'Um link de ativação foi enviado para seu e-mail. Por favor, ative sua conta para fazer login.')

            return redirect('login')  # Redireciona para a página de login
    else:
        form = SignUpForm()
    return render(request, 'register.html', {'form': form})


def activate(request, uidb64, token):
    try:
        # Decodificar o UID e obter o usuário
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('login')  # Redireciona para a página de login
    else:
        return HttpResponse("Link de ativação inválido!")
    
@login_required
def perfil(request):
    # Obtém o usuário logado
    user = request.user
    # Obtém o perfil estendido (UserPerfil) relacionado ao usuário
    try:
        perfil = user.user_name  # Usa o related_name definido no modelo
    except UserPerfil.DoesNotExist:
        # Se o perfil não existir, cria um perfil vazio
        perfil = UserPerfil(usuario=user)
        perfil.save()

    return render(request, 'perfil.html', {'perfil': user, 'user_perfil': perfil})

    
@login_required 
def alterar_senha(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Mantém o usuário logado após alterar a senha
            messages.success(request, 'Senha alterada com sucesso!')
            return redirect('perfil')
        else:
            messages.error(request, 'Corrija os erros abaixo.')
    else:
        form = PasswordChangeForm(request.user)
    
    return render(request, 'alterar-senha.html', {'form': form})

@login_required
def deletar_conta(request):
    if request.method == 'POST':
        # Apaga o usuário autenticado
        user = request.user
        user.delete()
        messages.success(request, "Sua conta foi deletada com sucesso.")
        return redirect('dashboard')  # Ou qualquer página que você queira redirecionar após a exclusão
    
    return render(request, 'deletar-conta.html')

@login_required
def completar_perfil(request):
    try:
        perfil = request.user.user_name
    except UserPerfil.DoesNotExist:
        perfil = UserPerfil(usuario=request.user)

    if request.method == "POST":
        # Adicione request.FILES aqui
        form = UserPerfilForm(request.POST, request.FILES, instance=perfil)
        if form.is_valid():
            form.save()
            return redirect('perfil')  # Redirecionar para a página de perfil
    else:
        form = UserPerfilForm(instance=perfil)

    return render(request, 'completar_perfil.html', {'form': form})


class CustomLoginView(LoginView):
    def get(self, request, *args, **kwargs):
        # Se o usuário está sendo redirecionado devido a uma tentativa de acesso sem login
        if not request.user.is_authenticated and 'next' in request.GET:
            messages.error(
                request, 'Você precisa estar logado para acessar esta página.')
        return super().get(request, *args, **kwargs)
    

def tabela_pedidos_cliente(request):
    # Recupera os pedidos do usuário autenticado
    pedidos = mainModels.Pedido.objects.filter(usuario=request.user)
    
    # Passa os pedidos para o template
    return render(request, 'tabela_pedidos_cliente.html', {'pedidos': pedidos})

def detalhes_pedido(request, pedido_id):
    pedido = get_object_or_404(mainModels.Pedido, id=pedido_id)
    return render(request, 'detalhes_pedido.html', {'pedido': pedido})

usuarios/templates/activation_email.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <title>Confirme seu email</title>
  </head>
  <body>
    <img width="100px" src="{{ STATIC_URL }}img/main_pages/ECOWATT.png" alt="">
    <p>Olá {{ user.username }},</p>
    <p>
      Para completar o seu cadastro, por favor, clique no link abaixo para
      ativar a sua conta:
    </p>
    <a href="http://{{ domain }}/user/activate/{{ uid }}/{{ token }}/"
      >Clique aqui para ativar sua conta</a
    >
    <br />
    <p>Atenciosamente, Ecowaat</p>
  </body>
</html>

usuarios/templates/completar_perfil.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Editar Perfil
{% endblock %}

{% block link_extras %}
    <link rel="stylesheet" href="{% static 'css/user/form-perfil.css' %}" />
    <link rel="stylesheet" href="{% static 'css/user/css-global.css' %}" />
{% endblock %}
{% block titulo_dashboard %}
  <div></div>
{% endblock %}
{% block main %}
<div class="perfil-container">
    
    <div class="perfil-info">
        {% include 'messages.html' %}
        <h2>Atualizar Perfil</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_foto">Foto de Perfil</label>
              {{ form.foto }}
              {% if form.foto.errors %}
              <div class="error-message">
                  {% for error in form.foto.errors %}
                      <p>{{ error }}</p>
                  {% endfor %}
              </div>
              {% endif %}
          </div>
            <div class="form-group">
                <label for="id_nome_completo">Nome Completo</label>
                {{ form.nome_completo }}
                {% if form.nome_completo.errors %}
                <div class="error-message">
                    {% for error in form.nome_completo.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_data_nascimento">Data de Nascimento</label>
                {{ form.data_nascimento }}
                {% if form.data_nascimento.errors %}
                <div class="error-message">
                    {% for error in form.data_nascimento.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_cep">CEP</label>
                {{ form.cep }}
                {% if form.cep.errors %}
                <div class="error-message">
                    {% for error in form.cep.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_cep">CPF</label>
                {{ form.cpf }}
                {% if form.cep.errors %}
                <div class="error-message">
                    {% for error in form.cep.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_endereco">Endereço</label>
                {{ form.endereco }}
                {% if form.endereco.errors %}
                <div class="error-message">
                    {% for error in form.endereco.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_estado">Estado</label>
                {{ form.estado }}
                {% if form.estado.errors %}
                <div class="error-message">
                    {% for error in form.estado.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="id_cidade">Cidade</label>
                {{ form.cidade }}
                {% if form.cidade.errors %}
                <div class="error-message">
                    {% for error in form.cidade.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_referencia">Referencia</label>
                {{ form.referencia }}
                {% if form.referencia.errors %}
                <div class="error-message">
                    {% for error in form.referencia.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary">Atualizar Perfil</button>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/user/api-cep.js' %}"></script>
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- jQuery Mask Plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script src="{% static 'js/user/cpf-mask.js' %}"></script>
{% endblock %}

usuarios/templates/detalhes_pedido.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Detalhes do Pedido #{{ pedido.id }}
{% endblock %}

{% block link_extras %}
    <link rel="stylesheet" href="{% static 'css/user/perfil.css' %}">
{% endblock %}

{% block main %}
<div class="container mt-5">
    <h2>Detalhes do Pedido #{{ pedido.id }}</h2>

    <div class="card mb-4">
        <div class="card-body">
            <p><strong>Data:</strong> {{ pedido.data_criacao|date:"d/m/Y H:i" }}</p>
            <p><strong>Marca:</strong> {{ pedido.marca }}</p>
            <p><strong>Quantidade:</strong> {{ pedido.quantidade }}</p>
            <p><strong>Forma de Pagamento:</strong> {{ pedido.pagamento }}</p>
            <p><strong>Tipo de Entrega:</strong> {{ pedido.tipo_entrega }}</p>
            <p><strong>Valor Total:</strong> R$ {{ pedido.valor_total|floatformat:2 }}</p>
        </div>
    </div>

    <a href="{% url 'tabela_pedidos_cliente' %}" class="btn btn-secondary">Voltar aos pedidos</a>
</div>
{% endblock %}

usuarios/templates/login.html
{% extends 'base.html' %} 

{% load static %} 

{% block navBar %}
<a href="{% url 'home' %}"
  ><img
    id="logomarca-img"
    src="{% static 'img/main_pages/PAYWATER.png' %}"
    alt=""
/></a>
    
{% endblock %} 
{% block title %}
    Login
{% endblock %}
{% block link_extras %}
<link rel="stylesheet" href="{% static 'css/user/form-login-register.css' %}" />
{% endblock %} {% block main %}
<div class="login-container">
  <div class="login-image">
    <img src="{% static 'img/user/economize-agua.png' %}" alt="Imagem decorativa" />
  </div>

  <div class="login-form">
    <h2>Entrar</h2>
    <!-- Exibir mensagens de sucesso ou erro -->
  {% include 'messages.html' %}
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_username">Usuário</label>
        {{ form.username }}
        {% if form.username.errors %}
        <div class="error-message">
          {% for error in form.username.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="id_password">Senha</label>
        {{ form.password }}
        {% if form.password.errors %}
        <div class="error-message">
          {% for error in form.password.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>

      {% if form.non_field_errors %}
      <div class="error-message">
        {% for error in form.non_field_errors %}
          <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}

      <button type="submit" class="btn-submit">Entrar</button>

      <div class="content-singup-login">
        <p>
          Ainda não possui uma conta?
          <span><a href="{% url 'register' %}">Criar conta.</a></span>
        </p>
      </div>
    </form>
  </div>
</div>
{% endblock %} {% block footer %}
<!-- Rodapé pode ser adicionado aqui, se necessário -->
{% endblock %}

usuarios/templates/logout.html
<form id="logout-form" action="{% url 'logout' %}" method="POST">
    {% csrf_token %}
    <i class="fas fa-sign-out"></i>
    <button type="button" onclick="confirmLogout()">Logout</button>
</form>

usuarios/templates/perfil.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Perfil
{% endblock %}

{% block link_extras %}
    <link rel="stylesheet" href="{% static 'css/user/perfil.css' %}" />
    <link rel="stylesheet" href="{% static 'css/user/css-global.css' %}" />
{% endblock %}
{% block main %}
<div class="perfil-container">
    <div class="d-flex align-items-center justify-content-end">
        <!-- Ícone de bars com submenu -->
        <div class="cog-container">
            <i class="fas fa-bars" id="bars-icon"></i>
            <!-- Submenu -->
            <div class="submenu" id="submenu">
                <ul>
                    <li><a href="{% url 'tabela_pedidos_cliente' %}"><i class="fas fa-check-circle"></i> Meus pedidos</a></li>
                    <li><a href=""><i class="fas fa-bar-chart"></i> Histórico de Consumo</a></li>
                    <li><a href=""><i class="fas fa-plug"></i> Equipamentos</a></li>
                </ul>
            </div>
        </div>
    </div>
    {% include 'messages.html' %}
    <h1>Meu Perfil</h1>
    
    <!-- Foto de perfil -->
    <div class="perfil-foto">
        {% if user_perfil.foto %}
            <img src="{{ user_perfil.foto.url }}" alt="Foto de perfil">
        {% else %}
            <i class="fas fa-user icone-usuario"></i>
        {% endif %}
    </div>
    
    <div class="perfil-info">
        <div class="info-item">
            <strong>Nome de usuário:</strong> <span>{{ perfil.username }}</span>
        </div>
        <div class="info-item">
            <strong>Email:</strong> <span>{{ perfil.email }}</span>
        </div>
        <div class="info-item">
            <strong>Nome Completo:</strong> <span>{{ user_perfil.nome_completo }}</span>
        </div>
        <div class="info-item">
            <strong>CPF:</strong> <span>{{ user_perfil.cpf }}</span>
        </div>
        <div class="info-item">
            <strong>Data de Nascimento:</strong> <span>{{ user_perfil.data_nascimento }}</span>
        </div>
        <div class="info-item">
            <strong>Endereço:</strong> <span>{{ user_perfil.endereco }}</span>
        </div>
    </div>
    
    <div class="perfil-actions">
        <a href="{% url 'completar-perfil' %}" class="btn btn-primary">Editar Perfil</a>
    </div>
</div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/user/bars.js' %}"></script>
{% endblock %}
    

usuarios/templates/register.html
{% extends 'base.html' %} {% load static %} 

{% block navBar %}
<a href="{% url 'home' %}"
  ><img
    id="logomarca-img"
    src="{% static 'img/main_pages/PAYWATER.png' %}"
    alt=""
/></a>

    
{% endblock %} 

{% block title %}
    Registrar
{% endblock %}

{% block link_extras %}
<link rel="stylesheet" href="{% static 'css/user/form-login-register.css' %}" />
{% endblock %} {% block main %}
<div class="login-container">
  <div class="login-image">
    <img src="{% static 'img/user/economize-agua.png' %}" alt="Imagem decorativa" />
  </div>
  <div class="login-form">
    <h2>Criar conta</h2>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_email">Email</label>
        {{ form.email }}
        {% if form.email.errors %}
        <div class="error-message">
          {% for error in form.email.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      
      <div class="form-group">
        <label for="id_username">Usuário</label>
        {{ form.username }}
        {% if form.username.errors %}
        <div class="error-message">
          {% for error in form.username.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      
      <div class="form-group">
        <label for="id_password1">Senha</label>
        {{ form.password1 }}
        {% if form.password1.errors %}
        <div class="error-message">
          {% for error in form.password1.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      
      <div class="form-group">
        <label for="id_password2">Confirmar Senha</label>
        {{ form.password2 }}
        {% if form.password2.errors %}
        <div class="error-message">
          {% for error in form.password2.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      
      <button type="submit" class="btn-submit">Entrar</button>
      
      <div class="content-singup-login">
        <p>
          Já possui uma conta?
          <span><a href="{% url 'login' %}">Entrar</a></span>
        </p>
      </div>
      
    </form>
  </div>
</div>
{% endblock %} {% block footer %}
<!-- Rodapé pode ser adicionado aqui, se necessário -->
{% endblock %}

usuarios/templates/tabela_pedidos_cliente.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Tabela Pedidos
{% endblock %}

{% block main %}
<div class="container mt-5">
    <h1>Meus Pedidos</h1>

    {% include 'messages.html' %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Data do Pedido</th>
                <th scope="col">Marca</th>
                <th scope="col">Total</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for pedido in pedidos %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th> <!-- aqui -->
                    <td>{{ pedido.data_criacao|date:"d/m/Y H:i" }}</td>
                    <td>{{ pedido.marca }}</td>
                    <td>R$ {{ pedido.valor_total|floatformat:2 }}</td>
                    <td>
                        <a href="{% url 'detalhes_pedido' pedido.id %}" class="btn btn-info btn-sm">Ver Detalhes</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">Você não tem pedidos.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'home' %}" class="btn btn-primary mt-3">Voltar para a Página Inicial</a>
</div>
{% endblock %}